spring.application.name=restaurant-platform
# Tell Spring Boot to create an SQLite file called 'restaurant.sqlite'
spring.datasource.url=jdbc:sqlite:restaurant.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC

# Tell Spring Boot how to auto-generate our Database Tables
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true